name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build_on_mac:

    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test --enable-code-coverage -v
      - name: Swift Coverage Report
        run: xcrun llvm-cov export -format="lcov" .build/debug/MachObjectPackageTests.xctest/Contents/MacOS/MachObjectPackageTests  -instr-profile .build/debug/codecov/default.profdata > .build/debug/codecov/info.lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

#  build_on_linux:
#
#    runs-on: ubuntu-latest
#    container:
#      image: swift:5.5.3-focal
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: recursive
#      - name: Build
#        run: swift build -v
#      - name: Run tests
#        run: swift test -v
